# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-eks-alb-controller
  description: This component creates a Helm release for alb-controller on an EKS cluster
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component
